apiVersion: v1
kind: Pod
metadata:
  name: myapp
  namespace: myapp
spec:
  containers:
  - name: myapp
    image: ghcr.io/go4clouds/myapp:v1.0
    resources:
      limits:
        cpu: "500m"
        memory: "200Mi"
      requests:
        cpu: "150m"
        memory: "100Mi"
    ports:
    - name: http
      containerPort: 8081
      protocol: TCP
    livenessProbe:
      httpGet:
          path: /
          port: http
      failureThreshold: 1
      initialDelaySeconds: 3
      periodSeconds: 5
