apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: newapp
  name: newapp
  namespace: newapp
spec:
  containers:
  - image: ghcr.io/go4clouds/newapp:latest
    name: newapp
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
